
server:
  port: 8888
  context-path: /config
spring:
  profiles:
    active: debug
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhenzhanlong/config-repo.git
          search-paths: config-repo
          username: zhanlong1988@126.com
          password: github147
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
  refresh:
      sensitive: false
